export enum ActionTypes {
    IMPORT_DOCUMENT = 'IMPORT_DOCUMENT',
    EXPORT_DOCUMENT = 'EXPORT_DOCUMENT',
    ADD_SLIDE = 'ADD_SLIDE',
    ADD_IMAGE_OBJECT = 'ADD_IMAGE_OBJECT',
    ADD_TEXT_OBJECT = 'ADD_TEXT_OBJECT',
    REMOVE_OBJECT = 'REMOVE_OBJECT',
    REMOVE_SLIDE = 'REMOVE_SLIDE',
    REORDER_SLIDE = 'REORDER_SLIDE',
    SET_FONT_SIZE = 'SET_FONT_SIZE',
    SET_FONT_WEIGHT = 'SET_FONT_WEIGHT',
    SET_OBJECT_ANGLE = 'SET_OBJECT_ANGLE',
    SET_OBJECT_POSITION = 'SET_OBJECT_POSITION',
    SET_OBJECT_SIZE = 'SET_OBJECT_SIZE',
    SET_PRESENTATION_TITLE = 'SET_PRESENTATION_TITLE',
    SET_SELECTED = 'SET_SELECTED',
    LOAD_EDITOR = 'LOAD_EDITOR'
}
